[package]
name = "praca-magisterska"
version = "0.1.0"
authors = ["evolveye <stolarski.paw@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
